server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ankitkumargcet/Microservices-Config-Store
          search-paths:
           - 'service-config/*service'
          #username: root
          #passphrase: 12345